# Generated by Django 3.2.5 on 2022-01-27 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=1, upload_to='portfolio/images/'),
            preserve_default=False,
        ),
    ]
